#cloud-config
package_update: true
package_upgrade: true

runcmd:
  - apt update
  - apt install -y xfce4 xfce4-goodies xrdp firefox
  - echo xfce4-session > /home/dotstatuser/.xsession
  - systemctl enable xrdp
  - systemctl start xrdp
  - apt install -y ca-certificates curl gnupg lsb-release git
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
  - apt update
  - apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - usermod -aG docker dotstatuser
  - systemctl enable docker
  - systemctl start docker
  - echo "127.0.0.1 host.docker.internal" >> /etc/hosts
  - echo "DOCKER_OPTS='--add-host=host.docker.internal:host-gateway'" > /etc/default/docker
  - systemctl daemon-reload
  - systemctl restart docker
  - su - dotstatuser -c "git clone https://github.com/omarof13/dotstatesuite.git"
  - su - dotstatuser -c "cd ~/dotstatesuite && find . -type f -name '*.sh' -exec chmod +x {} \\;"
  - su - dotstatuser -c "cd ~/dotstatesuite/demo && ./start.sh"
